# Generated by Django 4.0.3 on 2022-03-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Pt', 'Post admin'), ('Pr', 'Product admin')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Employee images/')),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('state', models.CharField(max_length=300, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=300, verbose_name='shahar')),
                ('street', models.CharField(blank=True, max_length=300, null=True, verbose_name="ko'cha")),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('company', models.ManyToManyField(related_name='employes', to='main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employes',
            },
        ),
    ]
